
    - id: heal_zwave_network
      alias: Heal Z-Wave Network
      initial_state: 'on'
      trigger:
        platform: time
        at: '3:00:00'
      condition:
        condition: time
        weekday:
          - fri
      action:
        service: zwave.heal_network

    - id: update_available_notification
      alias: "Update Available Notification"
      initial_state: 'on'
      trigger:
        platform: state
        entity_id: updater.updater
      action:
        - service: persistent_notification.create
          data:
            title: "Update Available"
            message: >
              Home Assistant {{ states('updater.updater') }} is available, please [update](https://home-assistant.io/getting-started/installation-raspberry-pi-all-in-one/#upgrading).
            notification_id: "update_available"


    - id: Flood_Lavavajillas_notification
      alias: 'Flood_LavavajillasNotify_MovedAlarm'
      initial_state: True
      trigger:
        platform: numeric_state
        entity_id: sensor.Flood_Lavavajillas_burglar
        above: 2
        below: 4
      action:
        - service: notify.matias
          data:
            message: Flood_Lavavajillas sensor has been moved
            title: Flood_Lavavajillas sensor moved

    - id: Flood_Lavavajillas_notification
      alias: 'Flood_LavavajillasNotify_FloodAlarm'
      initial_state: True
      trigger:
        platform: numeric_state
        entity_id: sensor.Flood_Lavavajillas_flood
        above: 1
        below: 3
      action:
        - service: notify.matias
          data:
            message: Flood_Lavavajillas sensor has been moved
            title: Flood_Lavavajillas sensor moved
        - service: persistent_notification.create
          data_template:
            message: "Flood_Lavavajillas flood alarm!"

    - id: Flood_Cocina_notification
      alias: 'Flood_CocinaNotify_MovedAlarm'
      initial_state: True
      trigger:
        platform: numeric_state
        entity_id: sensor.Flood_Cocina_burglar
        above: 2
        below: 4
      action:
        - service: notify.matias
          data:
            message: Flood_Cocina sensor has been moved
            title: Flood_Cocina sensor moved

    - id: Flood_Cocina_notification
      alias: 'Flood_CocinaNotify_FloodAlarm'
      initial_state: True
      trigger:
        platform: numeric_state
        entity_id: sensor.Flood_Cocina_flood
        above: 1
        below: 3
      action:
        - service: notify.matias
          data:
            message: Flood_Cocina sensor has been moved
            title: Flood_Cocina sensor moved
        - service: persistent_notification.create
          data_template:
            message: "Flood_Cocina flood alarm!"

    - id: Flood_Lavadora_notification
      alias: 'Flood_LavadoraNotify_MovedAlarm'
      initial_state: True
      trigger:
        platform: numeric_state
        entity_id: sensor.flood_lavadora_burglar
        above: 2
        below: 4
      action:
        - service: notify.matias
          data:
            message: Flood_Lavadora sensor has been moved
            title: Flood_Lavadora sensor moved

    - id: Flood_Lavadora_notification
      alias: 'Flood_LavadoraNotify_FloodAlarm'
      initial_state: True
      trigger:
        platform: numeric_state
        entity_id: sensor.flood_lavadora_flood
        above: 1
        below: 3
      action:
        - service: notify.matias
          data:
            message: Flood_Lavadora sensor flood alarm
            title: Flood_Lavadora sensor sensor flood alarm
        - service: persistent_notification.create
          data_template:
            message: "Flood_Lavadora flood alarm!"

    - id: Flood_Bano1_notification
      alias: 'Flood_BanoNotify_MovedAlarm'
      initial_state: True
      trigger:
        platform: numeric_state
        entity_id: sensor.flood_bano1_burglar
        above: 2
        below: 4
      action:
        - service: notify.matias
          data:
            message: Flood_Bano1 sensor has been moved
            title: Flood_Bano1 sensor moved

    - id: Flood_Bano1_notification
      alias: 'Flood_Bano1Notify_FloodAlarm'
      initial_state: True
      trigger:
        platform: numeric_state
        entity_id: sensor.flood_bano1_flood
        above: 1
        below: 3
      action:
        - service: notify.matias
          data:
            message: Flood_Bano1 sensor flood alarm
            title: Flood_Bano1 sensor sensor flood alarm
        - service: persistent_notification.create
          data_template:
            message: "Flood_Bano1 flood alarm!"

    - id: start_flood_notifications
      alias: Start flood automations
      initial_state: True
      trigger:
        platform: homeassistant
        event: start
      action:
        - delay:
            seconds: 3
        - service: automation.turn_on
          entity_id:
            - automation.Flood_LavavajillasNotify_FloodAlarm
            - automation.Flood_CocinaNotify_FloodAlarm
            - automation.Flood_LavadoraNotify_FloodAlarm
            - automation.Flood_Bano1Notify_FloodAlarm

 
    - id: iphonem_request_updates
      alias: Request updates from iphonem every hour
      initial_state: True
      trigger:
        platform: time
        minutes: 0
        seconds: 00
      condition:
        condition: numeric_state
        entity_id: sensor.iphonem_battery_level
        above: 10 
      action:
          - service: notify.ios_iphonem
            data:
                message: "request_location_update"

    - id: turnoffextlight1
      alias: Turn off external lights when closing main covers
      initial_state: True
      trigger:
        #change to cover.persiana_comedor_level
        #platform: numeric_state
        platform: state
        entity_id: cover.persiana_comedor_level
        from: 'open'
        to: 'closed'
        #entity_id: sensor.persiana_comedor_level_current_position
        #below: 20
      condition:
        condition: and
        conditions:
            - condition: or
              conditions:
                - condition: time
                  after: '20:00:00'
                - condition: time
                  before: '07:00:00'
            - condition: or
              conditions:
                - condition: numeric_state
                  entity_id: sensor.luces_jardin_power
                  above: 10
                - condition: numeric_state
                  entity_id: sensor.luces_jardin_power_2
                  above: 10
      action:
        - service: homeassistant.turn_off
          entity_id: switch.luces_jardin_switch
        - service: homeassistant.turn_off
          entity_id: switch.luces_jardin_switch_2
        - service: notify.ios_iphonem
          data:
            title: "Home Assistant"
            message: "Auto turned off external lights (closed shutter)"

    - id: turnofflightsatnight
      alias: Turn off external lights we forgot about at night
      initial_state: True
      trigger:
        platform: time
        hours: 00
        minutes: 00
        seconds: 00
      condition:
        condition: and
        conditions:
            - condition: or
              conditions:
                - condition: time
                  after: '22:00:00'
                - condition: time
                  before: '07:00:00'
            - condition: or
              conditions:
                - condition: numeric_state
                  entity_id: sensor.luces_jardin_power
                  above: 10
                - condition: numeric_state
                  entity_id: sensor.luces_jardin_power_2
                  above: 10
      action:
        # - delay: '00:{{ (range(1, 59)|random|int) }}:00'
        - service: homeassistant.turn_off
          entity_id: switch.luces_jardin_switch
        - service: homeassistant.turn_off
          entity_id: switch.luces_jardin_switch_2
        - service: notify.ios_iphonem
          data:
            title: "Home Assistant"
            message: "Auto turned off external lights (turnofflightsatnight)"

    - id: turnonextlight_open
      alias: Turn on external lights when opening main covers at night.
      initial_state: True
      trigger:
        platform: numeric_state
        entity_id: sensor.persiana_comedor_level_current_position
        below: 85
      condition:
        condition: and
        conditions:
            - condition: numeric_state
              entity_id: sensor.solar_angle
              below: 0
            - condition: and
              conditions:
                - condition: numeric_state
                  entity_id: sensor.luces_jardin_power
                  below: 10
                - condition: numeric_state
                  entity_id: sensor.luces_jardin_power_2
                  below: 10
      action:
        - service: homeassistant.turn_on
          entity_id: switch.luces_jardin_switch
        - service: homeassistant.turn_on
          entity_id: switch.luces_jardin_switch_2
        - service: notify.ios_iphonem
          data:
            title: "Home Assistant"
            message: "Auto turned on external lights"

    - id: turnoffextlight_sun
      alias: Turn off external lights at dawn.
      initial_state: True
      trigger:
        platform: numeric_state
        entity_id: sensor.solar_angle
        above: 5
      condition:
        condition: or
        conditions:
          - condition: numeric_state
            entity_id: sensor.luces_jardin_power
            above: 10
          - condition: numeric_state
            entity_id: sensor.luces_jardin_power_2
            above: 10
      action:
        - service: homeassistant.turn_off
          entity_id: switch.luces_jardin_switch
        - service: homeassistant.turn_off
          entity_id: switch.luces_jardin_switch_2
        - service: notify.ios_iphonem
          data:
            title: "Home Assistant"
            message: "Auto turned off external lights at dawn"

    - id: turnontoilet_onpir_1
      alias: Turn on toilet1 light if there is movement and it's dark
      trigger:
        platform: state
        entity_id: binary_sensor.pir_bano_sensor
        to: 'on'
      condition:
        condition: and
        conditions:
            - condition: numeric_state
              entity_id: sensor.pir_bano_luminance
              below: 5
            - condition: numeric_state
              entity_id: sensor.luces_bano1_power
              below: 10

      action:
        - service: homeassistant.turn_on
          entity_id: switch.luces_bano1_switch_2

    - id: turnofftoilet_nopir_1
      alias: Turn off toilet1 lights 10 minutes after last movement
      trigger:
        platform: state
        entity_id: binary_sensor.pir_bano_sensor
        to: 'off'
        for:
          minutes: 10
      condition:
        condition: or          
        conditions:
          - condition: state
            entity_id: switch.luces_bano1_switch_2
            state: "on"
          - condition: state
            entity_id: switch.luces_bano1_switch_3
            state: "on"            
      action:
        - service: homeassistant.turn_off
          entity_id: switch.luces_bano1_switch
        - service: homeassistant.turn_off
          entity_id: switch.luces_bano1_switch_2
        - service: homeassistant.turn_off
          entity_id: switch.luces_bano1_switch_3
        - service: notify.ios_iphonem
          data:
            title: "Home Assistant"
            message: "Auto turned off toilet lights (forgot)"

    - id: wifi_kids_off
      initial_state: True
      alias: Turn off wifi for kids
      trigger:
        platform: time
        hours: 20
        minutes: 00
        seconds: 00
      condition:
        condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.enable_wifi_kids
            state: "on"
          - condition: time
            weekday:
              - mon
              - tue
              - wed
              - thu
              - sun
      action:
        - service: switch.turn_off
          entity_id: switch.wifi_kids
        - service: notify.ios_iphonem
          data:
            title: "Home Assistant"
            message: "Wifi OFF"

    - id: wifi_kids_on
      initial_state: True
      alias: Turn on wifi for kids
      trigger:
        platform: time
        hours: 10
        minutes: 00
        seconds: 00
      condition:
        condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.enable_wifi_kids
            state: "on"
          - condition: time
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
      action:
        - service: switch.turn_on
          entity_id: switch.wifi_kids


    - id: auto_sprinkler_morning
      initial_state: True
      alias: Activate automatic sprinkler (morning
      trigger:
        platform: sun
        event: sunrise
        offset: '01:00:00'
      condition:
        condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.enable_sprinkler_auto
            state: "on"
          - condition: time
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
              - sat
              - sun
      action:
        - service: switch.turn_on
          entity_id: switch.sprinkler1_switch
        - delay: '00:05:00'
        - service: switch.turn_off
          entity_id: switch.sprinkler1_switch
        - service: switch.turn_on
          entity_id: switch.sprinkler1_switch_2
        - delay: '00:05:00'
        - service: switch.turn_off
          entity_id: switch.sprinkler1_switch_2


    - id: auto_sprinkler_evening1
      initial_state: True
      alias: Activate automatic sprinkler (evening)
      trigger:
        platform: sun
        event: sunset
        offset: '-01:00:00'
      condition:
        condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.enable_sprinkler_auto
            state: "on"
          - condition: time
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
              - sat
              - sun
      action:
        - service: switch.turn_on
          entity_id: switch.sprinkler1_switch
        - delay: '00:01:00'
        - service: switch.turn_off
          entity_id: switch.sprinkler1_switch
        - service: switch.turn_on
          entity_id: switch.sprinkler1_switch_2
        - delay: '00:05:00'
        - service: switch.turn_off
          entity_id: switch.sprinkler1_switch_2

    - id: suelo_radiante_temp_alert
      alias: Alert on temperature
      initial_state: True
      trigger:
        platform: numeric_state
        entity_id: sensor.suelo_radiante_temperature
        above: 23.0
        below: 16.0
      action:
          - service: notify.ios_iphonem
            data:
              title: "Home Assistant"
              message: "Temperature alert {{ states.climate.suelo_radiante.attributes.current_temperature }}"

    - id: suelo_radiante_night_off
      alias: Lower target temperature over night
      initial_state: True
      trigger:
        platform: time
        hours: 00
        minutes: 00
        seconds: 00 
      action:
          - service: climate.set_temperature
            data_template:
              entity_id: climate.suelo_radiante
              temperature: '{{ states.climate.suelo_radiante.attributes.temperature - 2 }}'
          - service: notify.ios_iphonem
            data:
              title: "Home Assistant"
              message: "Setting target temperature to {{ states.climate.suelo_radiante.attributes.temperature - 2 }}"

    - id: suelo_radiante_night_on
      alias: Restore target temperature
      initial_state: True
      trigger:
        platform: time
        hours: 07
        minutes: 00
        seconds: 00 
      condition:
        - condition: template
          value_template: '{{ states.climate.suelo_radiante.attributes.temperature < "20.1" }}'
      action:
          - service: climate.set_temperature
            data_template:
              entity_id: climate.suelo_radiante
              temperature: '{{ states.climate.suelo_radiante.attributes.temperature + 2 }}'

    - id: suelo_radiante_cleaning_off
      alias: Deactivate heating
      initial_state: True
      trigger:
        platform: time
        hours: 09
        minutes: 00
        seconds: 00
      condition:
      - condition: time
        weekday:
          - tue
          - fri
      action:
          - service: climate.set_temperature
            data_template:
              entity_id: climate.suelo_radiante
              temperature: '{{ states.climate.suelo_radiante.attributes.temperature - 10 }}'

    - id: suelo_radiante_cleaning_on
      alias: Reactivate heating
      initial_state: True
      trigger:
        platform: time
        hours: 13
        minutes: 00
        seconds: 00
      condition:
      - condition: time
        weekday:
          - tue
          - fri
      action:
          - service: climate.set_temperature
            data_template:
              entity_id: climate.suelo_radiante
              temperature: '{{ states.climate.suelo_radiante.attributes.temperature + 10 }}'

    - id: alert_missing_update_suelo_radiante
      alias: Notify missing updates from suelo_radiante
      trigger:
        - platform: time
          hours: '/1'
          minutes: 00
          seconds: 00
      condition:
        condition: and
        conditions:
        - condition: template
          value_template: '{{ (as_timestamp(now()) - as_timestamp(states.climate.suelo_radiante.last_updated)) > 3600 }}'
        - condition: state
          entity_id: input_boolean.alarm_suelo_radiante
          state: 'off'
      action:
        - service: homeassistant.turn_on
          data: 
            entity_id: input_boolean.alarm_suelo_radiante
        - service: notify.ios_iphonem
          data:
            title: "Home Assistant"
            message: "Temperature alert {{ states.climate.suelo_radiante.attributes.current_temperature }}"

############################################################################################################################################
    #Dash Buttons
    - id: dashbutton01
      alias: "6c:56:97:f7:89:3f"
      initial_state: 'on'
      trigger:
        platform: event
        event_type: myevent_dashbutton01
      action:
        - service: switch.toggle
          entity_id: switch.luces_jardin_switch_2

    - id: dashbutton02
      alias: "fc:65:de:c3:e2:30"
      initial_state: 'on'
      trigger:
        platform: event
        event_type: myevent_dashbutton02
      action:
        - service: switch.toggle
          entity_id: switch.luces_pasillo_switch_2

    - id: dashbutton03
      alias: "18:74:2e:1c:8a:63"
      initial_state: 'on'
      trigger:
        platform: event
        event_type: myevent_dashbutton03
      action:
        - service: shell_command.ps4standby


    - id: dashbutton04
      alias: "18:74:2e:1c:8a:99"
      initial_state: 'on'
      trigger:
        platform: event
        event_type: myevent_dashbutton99
      action:
        - service: switch.turn_off
          entity_id: switch.wifi_kids
        - service: notify.ios_iphonem
          data:
            title: "Home Assistant"
            message: "Wifi OFF"
        - delay:
            seconds: "3600"
        - service: switch.turn_on
          entity_id: switch.wifi_kids
        - service: notify.ios_iphonem
          data:
            title: "Home Assistant"
            message: "Wifi ON"

